config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/signin',  to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  get '/signup',  to: 'users#new'  
  resources :users,  only: [:new, :create, :edit, :update, :index]
  resources :items,  only: [:create, :index]
  resources :menus,  only: [:new, :show]
  resources :fillings, only: [:create, :update]
  resources :orders, only: [:create, :index]
  get '/orders/to-current-order/:item_name', to: 'orders#add_to_current_order'
  get '/orders/clear-order', to: 'orders#clear_order'
  get '/menus/to-current-menu/:item_name', to: 'menus#add_to_current_menu'
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :fillings, dependent:   :destroy
  has_many :items,    through:     :fillings
  
  validates :menu_date, presence: true

  def Menu.add_item_to_today_menu(item)
    menu = Menu.today_menu
    unless menu.items.include?(item)
      menu.items << item
    end
  end

  def Menu.today_menu
    menu = Menu.find_by(menu_date: Date.today)
    unless menu
      menu = Menu.create(menu_date: Date.today)
    end
    menu
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  include MenusHelper

  before_action :access_check, only: [:new, :create]
  before_action :logged_in_user, only: [:show]

  def show
    if pmenu = params[:menu]
      @menu = Menu.find_by(menu_date: pmenu[:menu_date])
      unless @menu
        @menu = Menu.last
        flash[:info] = "There is no menu for this date. The last existing menu is loaded."
        redirect_to @menu
        return
      end
    else
      @menu = Menu.find_by(id: params[:id])
    end
    
    if params[:item]
      kind = params[:item][:kind]
    else
      kind = 'first'
    end

    @items = @menu.items.where("kind = ?", kind).paginate(page: params[:page])
    @order = Order.new
    store_location
  end

  def new
    if params[:item]
      kind = params[:item][:kind]
    else
      kind = 'first'
    end
    @menu = Menu.today_menu
    @items = Item.where("kind=?", kind).paginate(page: params[:page])
    store_location
  end

  def add_to_current_menu
    item = Item.find_by(name: params[:item_name])
    Menu.add_item_to_today_menu(item)
    redirect_back_or(new_menu_path)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
  def last_menu
    @last_menu = Menu.last
  end

  def all_menu_dates
    menus = Menu.all
    unless menus
      return nil
    end
    dates = []
    menus.each do |menu|
      unless dates.index(menu.menu_date)
        dates << menu.menu_date
      end
    end
    dates
  end
end

app/views/menus/_current_menu_form.html.erb
<%= form_with model: @menu, local: true, id: 'menu_form' do %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table">
      <thead>    
        <tr>
          <th>Course</th>
          <th>Kind</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody class="new_menu_items">
        <% @menu.items.each do |item| %>
          <tr>
            <td><%= item.name %></td> 
            <td><%= item.kind %></td>
            <td><%= item.price %></td> 
          </tr> 
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td>Total items: <%= @menu.items.count %></td>
        </tr>
      </tfoot>
      </tr>
    </table>
  </div>
</div>

<% end %>

app/views/menus/_current_order.html.erb
<%= form_with model: @order do %>
<%= render 'shared/error_messages', object: @order %>

<table>
  <thead>    
    <tr>
      <th>Course</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="fcname"><%= current_order_item_name("first") %></td>
      <td class="fcprice"><%= current_order_item_price("first") %></td>
    </tr>
    <tr>
      <td class="mcname"><%= current_order_item_name("main") %></td>
      <td class="mcprice"><%= current_order_item_price("main") %></td>
    </tr>
    <tr>
      <td class="dname"><%= current_order_item_name("drink") %></td>
      <td class="dprice"><%= current_order_item_price("drink") %></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td>Total price:</td>
      <td class="tprice"><%= current_order_total_price %></td>
    </tr>
  </tfoot>
  </tr>
</table>
<br>

<%= link_to 'Clear order', clear_order_link %>

  <%= hidden_field(:order, :first_course, value: current_order_item_name("first")) %>
  <%= hidden_field(:order, :main_course,  value: current_order_item_name("main")) %>
  <%= hidden_field(:order, :drink,        value: current_order_item_name("drink")) %>
  <%= hidden_field(:order, :price,        value: current_order_total_price) %>
  <%= hidden_field(:order, :order_date,   value: Date.today) %>
  <%= submit_tag("Make order!") %>
<% end %>

app/views/menus/_current_order_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @order, local: true, id: 'order_form' do %>

    <table class="table">
      <thead>    
        <tr>
          <th>Course</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="fcname"><%= current_order_item_name("first") %></td>
          <td class="fcprice"><%= current_order_item_price("first") %></td>
        </tr>
        <tr>
          <td class="mcname"><%= current_order_item_name("main") %></td>
          <td class="mcprice"><%= current_order_item_price("main") %></td>
        </tr>
        <tr>
          <td class="dname"><%= current_order_item_name("drink") %></td>
          <td class="dprice"><%= current_order_item_price("drink") %></td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <td>Total price:</td>
          <td class="tprice"><%= current_order_total_price %></td>
        </tr>
      </tfoot>
      </tr>
    </table>
    <br>

    <%= link_to 'Clear order', clear_order_link, class: "btn btn-primary" %>

    <%= hidden_field(:order, :first_course, value: current_order_item_name("first")) %>
    <%= hidden_field(:order, :main_course,  value: current_order_item_name("main")) %>
    <%= hidden_field(:order, :drink,        value: current_order_item_name("drink")) %>
    <%= hidden_field(:order, :price,        value: current_order_total_price) %>
    <%= hidden_field(:order, :order_date,   value: Date.today) %>
    <%= submit_tag("Make order!", class: "btn btn-primary") %>
    <% end %>
  </div>
</div>

app/views/menus/_date_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: menu_path, method: "get", selected: @menu.menu_date, local: true) do %>
      <%= select("menu", "menu_date", all_menu_dates.collect{|date| [date, date]}, {},
          { class: 'form-control' }) %>
      <%= submit_tag "Go", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/menus/_kind_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if controller_name == "menus" && action_name == "show" %>
      <%= form_with(url: menu_path, method: "get", local: true) do %>
        <%= label_tag("item_kind", "Item's kind:") %>
        <%= select("item", "kind", Item.all_kinds.collect{|kind| [kind, kind]}, {},
            { class: 'form-control' } ) %>
        <%= date_field("menu", "menu_date", value: @menu.menu_date, hidden: true) %>
        <%= submit_tag("Search", class: "btn btn-primary") %>
      <% end %>
    <% elsif controller_name == "menus" && action_name == "new" %>
      <%= form_with(url: new_menu_path, method: "get", local: true) do %>
        <%= label_tag("item_kind", "Item's kind:") %>
        <%= select("item", "kind", Item.all_kinds.collect{|kind| [kind, kind]}, {},
            {class: 'form-control'} ) %>
        <%= date_field("menu", "menu_date", value: @menu.menu_date, hidden: true) %>
        <%= submit_tag("Search", class: "btn btn-primary") %>
      <% end %>
    <% else %>
      <p>Form render error</p>
    <% end %>
  </div>
</div>

app/views/menus/new.html.erb
<% provide(:title, 'Edit today menu') %>
<h1>Edit menu for today</h1>

<%= render 'kind_form' %>
<%= render 'current_menu_form' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= will_paginate @items %>
    <ul id="items_list">
      <%= render @items %>
    </ul>
    <%= will_paginate @items %>
  </div>
</div>

app/views/menus/show.html.erb
<% provide(:title, 'Menu') %>
<h1>Menu for: <%= @menu.menu_date %></h1>

<%= render 'date_form' %>
<%= render  'kind_form' %>
<%= render 'current_order_form' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= will_paginate @items %>
    <ul class="list-group">
      <%= render @items %>
    </ul>
    <%= will_paginate @items %>
  </div>
</div>