config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/signin',  to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  get '/signup',  to: 'users#new'  
  resources :users,  only: [:new, :create, :edit, :update, :index]
  resources :items,  only: [:create, :index]
  resources :menus,  only: [:new, :show]
  resources :fillings, only: [:create, :update]
  resources :orders, only: [:create, :index]
  get '/orders/to-current-order/:item_name', to: 'orders#add_to_current_order'
  get '/orders/clear-order', to: 'orders#clear_order'
  get '/menus/to-current-menu/:item_name', to: 'menus#add_to_current_menu'
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    The Lunch Ordering Service - 2019
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "lunch ordering", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Menu <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Show menu", last_menu %></li>
                <li><%= link_to "Edit today menu", new_menu_path %></li>
              </ul>
            </li>
            <li><%= link_to "Orders", orders_path %></li>
            <li><%= link_to "Items", items_path %></li>
            <li><%= link_to "Users", users_path %></li>          
          <% else %>
            <li><%= link_to "Menu", last_menu %></li>
            <li><%= link_to "My orders", orders_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit account", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>